language: python

python:
    - '3.6'

services:
  - xvfb

before_install:
  - pip install coverage
  - pip install coveralls
  - pip install python-coveralls

install:
  - git clone https://github.com/fbcotter/pytorch_wavelets
  - cd pytorch_wavelets
  - pip install .
  - git clone https://github.com/edarragh/demeter
  - cd demeter
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - coverage run -m unittest test_demeter.py

after_success:
  - coveralls
