language: python

python:
    - '3.6'

services:
  - xvfb

before_install:
  - pip install coverage==4.5.4 # Temp fix
  - pip install coveralls
  - pip install python-coveralls

install:
  - git clone https://github.com/edarragh/demeter
  - cd demeter
  - pip install -e . -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - coverage run --source ovejero -m unittest -v *_tests.py

after_success:
  - coveralls
